'use client'

import { useState } from 'react'
import axios from 'axios'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'

export default function ReviewWorkflow() {
  const [workflowId, setWorkflowId] = useState('')
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)
  const [reviewResult, setReviewResult] = useState<string | null>(null)

  const exportToPDF = () => {
    if (!summary) return
    
    // Create a simple text-based report
    const reportContent = `
LOAN APPLICATION REPORT
========================
Generated: ${new Date().toLocaleString()}
Workflow ID: ${workflowId}

APPLICANT INFORMATION
---------------------
Name: ${summary.application?.name || 'N/A'}
Applicant ID: ${summary.application?.applicant_id || 'N/A'}
Loan Amount: $${summary.application?.amount?.toLocaleString() || 'N/A'}
Monthly Income: $${summary.application?.income?.toLocaleString() || 'N/A'}
Monthly Expenses: $${summary.application?.expenses?.toLocaleString() || 'N/A'}

AI RECOMMENDATION
-----------------
Decision: ${summary.suggested_decision?.decision?.toUpperCase() || 'PENDING'}
Confidence: ${summary.suggested_decision?.confidence || 'N/A'}

Reasoning:
${summary.suggested_decision?.reasoning || 'No reasoning provided'}

CREDIT ASSESSMENT
-----------------
${JSON.stringify(summary.assessments?.credit || {}, null, 2)}

INCOME ASSESSMENT
-----------------
${JSON.stringify(summary.assessments?.income || {}, null, 2)}

EXPENSE ASSESSMENT
------------------
${JSON.stringify(summary.assessments?.expense || {}, null, 2)}

========================
Report generated by AI Loan Underwriter Pro
Developed by Norvin Samson Anthony
    `.trim()

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `loan-report-${workflowId}-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
  }

  const fetchSummary = async () => {
    if (!workflowId.trim()) {
      setError('Please enter a workflow ID')
      return
    }

    setLoading(true)
    setError(null)
    setSummary(null)
    setReviewResult(null)

    try {
      const response = await axios.get(`${API_URL}/workflow/${workflowId}/summary`)
      setSummary(response.data.summary)
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message || 'Failed to fetch summary')
    } finally {
      setLoading(false)
    }
  }

  const handleReview = async (action: 'approve' | 'reject') => {
    setLoading(true)
    setError(null)
    setReviewResult(null)

    try {
      await axios.post(`${API_URL}/workflow/${workflowId}/review`, {
        action,
        note: `${action === 'approve' ? 'Approved' : 'Rejected'} via UI`
      })
      setReviewResult(action === 'approve' ? 'Loan Approved! ✅' : 'Loan Rejected ❌')
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message || 'Failed to submit review')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Review Loan Application</h2>

      {/* Workflow ID Input */}
      <div className="mb-6">
        <label htmlFor="workflowId" className="block text-sm font-medium text-gray-700 mb-2">
          Workflow ID
        </label>
        <div className="flex gap-3">
          <input
            type="text"
            id="workflowId"
            value={workflowId}
            onChange={(e) => setWorkflowId(e.target.value)}
            placeholder="loan-12345"
            className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
          <button
            onClick={fetchSummary}
            disabled={loading}
            className="px-6 py-2 bg-emerald-600 text-white rounded-lg font-medium hover:bg-emerald-700 transition-colors disabled:bg-gray-400"
          >
            {loading ? 'Loading...' : 'Fetch Details'}
          </button>
        </div>
      </div>

      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
          <p className="text-red-800 font-medium">Error</p>
          <p className="text-red-600 text-sm mt-1">{error}</p>
        </div>
      )}

      {reviewResult && (
        <div className={`mb-6 p-4 border rounded-lg ${
          reviewResult.includes('Approved') 
            ? 'bg-green-50 border-green-200' 
            : 'bg-red-50 border-red-200'
        }`}>
          <p className={`font-medium text-lg ${
            reviewResult.includes('Approved') ? 'text-green-800' : 'text-red-800'
          }`}>
            {reviewResult}
          </p>
        </div>
      )}

      {summary && (
        <div className="space-y-6">
          {/* Application Details */}
          <div className="bg-white border border-gray-200 rounded-lg p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">📋 Application Details</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-gray-600">Applicant Name</p>
                <p className="font-medium">{summary.application?.name || 'N/A'}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Applicant ID</p>
                <p className="font-medium">{summary.application?.applicant_id || 'N/A'}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Loan Amount</p>
                <p className="font-medium text-lg">${summary.application?.amount?.toLocaleString() || 0}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Monthly Income</p>
                <p className="font-medium">${summary.application?.income?.toLocaleString() || 0}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Monthly Expenses</p>
                <p className="font-medium">${summary.application?.expenses?.toLocaleString() || 0}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Net Income</p>
                <p className="font-medium text-green-600">
                  ${((summary.application?.income || 0) - (summary.application?.expenses || 0)).toLocaleString()}
                </p>
              </div>
            </div>
          </div>

          {/* AI Assessments */}
          {summary.assessments && (
            <div className="bg-white border border-gray-200 rounded-lg p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">🤖 AI Assessments</h3>
              <div className="space-y-6">
                {Object.entries(summary.assessments).map(([key, assessment]: [string, any]) => (
                  <div key={key} className="border-l-4 border-emerald-500 pl-4 bg-emerald-50 p-4 rounded-r-lg">
                    <h4 className="font-semibold text-gray-900 capitalize mb-3 text-lg">
                      {key === 'credit' && '💳 '}
                      {key === 'income' && '💰 '}
                      {key === 'expense' && '📊 '}
                      {key.replace('_', ' ')} Assessment
                    </h4>
                    
                    {/* Key Metrics */}
                    <div className="grid grid-cols-2 gap-3 mb-3">
                      {assessment.credit_score && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Credit Score</p>
                          <p className="text-lg font-bold text-emerald-600">{assessment.credit_score}</p>
                        </div>
                      )}
                      {assessment.risk_level && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Risk Level</p>
                          <p className={`text-lg font-bold ${
                            assessment.risk_level === 'low' ? 'text-green-600' :
                            assessment.risk_level === 'medium' ? 'text-yellow-600' :
                            'text-red-600'
                          }`}>
                            {assessment.risk_level?.toUpperCase()}
                          </p>
                        </div>
                      )}
                      {assessment.income && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Monthly Income</p>
                          <p className="text-lg font-bold text-emerald-600">${assessment.income?.toLocaleString()}</p>
                        </div>
                      )}
                      {assessment.annual_income && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Annual Income</p>
                          <p className="text-lg font-bold text-emerald-600">${assessment.annual_income?.toLocaleString()}</p>
                        </div>
                      )}
                      {assessment.income_to_loan_ratio && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Income/Loan Ratio</p>
                          <p className={`text-lg font-bold ${
                            assessment.income_to_loan_ratio >= 2.5 ? 'text-green-600' : 'text-red-600'
                          }`}>
                            {assessment.income_to_loan_ratio}x
                          </p>
                        </div>
                      )}
                      {assessment.affordability_ok !== undefined && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Affordability</p>
                          <p className={`text-lg font-bold ${
                            assessment.affordability_ok ? 'text-green-600' : 'text-red-600'
                          }`}>
                            {assessment.affordability_ok ? '✅ OK' : '❌ FAIL'}
                          </p>
                        </div>
                      )}
                      {assessment.monthly_expenses && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Monthly Expenses</p>
                          <p className="text-lg font-bold text-gray-700">${assessment.monthly_expenses?.toLocaleString()}</p>
                        </div>
                      )}
                      {assessment.disposable_income !== undefined && (
                        <div className="bg-white p-3 rounded-lg">
                          <p className="text-xs text-gray-500">Disposable Income</p>
                          <p className={`text-lg font-bold ${
                            assessment.disposable_income > 0 ? 'text-green-600' : 'text-red-600'
                          }`}>
                            ${assessment.disposable_income?.toLocaleString()}
                          </p>
                        </div>
                      )}
                    </div>
                    
                    {/* AI Analysis Text */}
                    {assessment.assessment && (
                      <div className="bg-white p-4 rounded-lg mt-3">
                        <p className="text-xs text-gray-500 mb-2 font-semibold">AI Analysis:</p>
                        <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                          {assessment.assessment}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* AI Decision */}
          {summary.suggested_decision && (
            <div className="bg-gradient-to-br from-emerald-50 via-teal-50 to-green-50 border-2 border-emerald-400 rounded-xl p-6 shadow-lg">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                  🤖 AI Recommendation
                </h3>
                <span className="px-3 py-1 bg-emerald-600 text-white text-xs font-semibold rounded-full">
                  Powered by AWS Bedrock
                </span>
              </div>
              
              {/* Main Decision Card */}
              <div className="bg-white rounded-xl p-6 shadow-md mb-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-500 mb-2">Final Decision</p>
                    <div className="flex items-center gap-3">
                      <p className={`text-4xl font-black ${
                        summary.suggested_decision.decision === 'approve' 
                          ? 'text-green-600' 
                          : summary.suggested_decision.decision === 'reject'
                          ? 'text-red-600'
                          : 'text-yellow-600'
                      }`}>
                        {summary.suggested_decision.decision === 'approve' && '✅'}
                        {summary.suggested_decision.decision === 'reject' && '❌'}
                        {summary.suggested_decision.decision === 'review' && '⚠️'}
                      </p>
                      <div>
                        <p className={`text-3xl font-bold ${
                          summary.suggested_decision.decision === 'approve' 
                            ? 'text-green-600' 
                            : summary.suggested_decision.decision === 'reject'
                            ? 'text-red-600'
                            : 'text-yellow-600'
                        }`}>
                          {summary.suggested_decision.decision?.toUpperCase()}
                        </p>
                        {summary.suggested_decision.confidence && (
                          <p className="text-sm text-gray-600">
                            {summary.suggested_decision.confidence} confidence
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                  
                  {/* Confidence Meter */}
                  {summary.suggested_decision.confidence && (
                    <div className="text-right">
                      <p className="text-sm text-gray-500 mb-2">Confidence Level</p>
                      <div className="flex items-center gap-2">
                        <div className="w-32 h-3 bg-gray-200 rounded-full overflow-hidden">
                          <div 
                            className={`h-full rounded-full ${
                              summary.suggested_decision.confidence === 'high' ? 'bg-green-500 w-full' :
                              summary.suggested_decision.confidence === 'medium' ? 'bg-yellow-500 w-2/3' :
                              'bg-red-500 w-1/3'
                            }`}
                          />
                        </div>
                        <span className="text-lg font-bold text-emerald-600 capitalize">
                          {summary.suggested_decision.confidence}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              </div>
              
              {/* Key Factors Grid */}
              <div className="grid grid-cols-3 gap-3 mb-4">
                {summary.suggested_decision.credit_risk && (
                  <div className="bg-white p-4 rounded-lg text-center shadow-sm border-l-4 border-emerald-500">
                    <p className="text-xs text-gray-500 mb-1">💳 Credit Risk</p>
                    <p className={`text-xl font-bold ${
                      summary.suggested_decision.credit_risk === 'low' ? 'text-green-600' :
                      summary.suggested_decision.credit_risk === 'medium' ? 'text-yellow-600' :
                      'text-red-600'
                    }`}>
                      {summary.suggested_decision.credit_risk?.toUpperCase()}
                    </p>
                  </div>
                )}
                {summary.suggested_decision.income_adequate !== undefined && (
                  <div className="bg-white p-4 rounded-lg text-center shadow-sm border-l-4 border-teal-500">
                    <p className="text-xs text-gray-500 mb-1">💰 Income Check</p>
                    <p className={`text-xl font-bold ${
                      summary.suggested_decision.income_adequate ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {summary.suggested_decision.income_adequate ? '✅ PASS' : '❌ FAIL'}
                    </p>
                  </div>
                )}
                {summary.suggested_decision.expenses_manageable !== undefined && (
                  <div className="bg-white p-4 rounded-lg text-center shadow-sm border-l-4 border-green-500">
                    <p className="text-xs text-gray-500 mb-1">📊 Expenses Check</p>
                    <p className={`text-xl font-bold ${
                      summary.suggested_decision.expenses_manageable ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {summary.suggested_decision.expenses_manageable ? '✅ PASS' : '❌ FAIL'}
                    </p>
                  </div>
                )}
              </div>
              
              {/* Detailed Reasoning */}
              {summary.suggested_decision.reasoning && (
                <div className="bg-white p-5 rounded-lg shadow-sm border border-emerald-200">
                  <div className="flex items-start gap-3">
                    <span className="text-2xl">📝</span>
                    <div className="flex-1">
                      <p className="text-sm font-semibold text-gray-700 mb-2">AI Reasoning & Analysis:</p>
                      <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                        {summary.suggested_decision.reasoning}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Review Actions */}
          {!reviewResult && (
            <div className="bg-white border-2 border-gray-200 rounded-xl p-6 shadow-md">
              <h3 className="text-xl font-bold text-gray-900 mb-2 flex items-center gap-2">
                💼 Your Decision
              </h3>
              <p className="text-gray-600 mb-6">
                Review the AI assessment above and make your final decision:
              </p>
              <div className="flex gap-4">
                <button
                  onClick={exportToPDF}
                  className="px-6 py-3 bg-teal-600 text-white rounded-lg font-semibold hover:bg-teal-700 transition-all hover:shadow-lg flex items-center gap-2"
                >
                  📄 Export Report
                </button>
                <div className="flex-1"></div>
                <button
                  onClick={() => handleReview('reject')}
                  disabled={loading}
                  className="px-8 py-3 bg-red-600 text-white rounded-lg font-semibold hover:bg-red-700 transition-all hover:shadow-lg disabled:bg-gray-400 disabled:cursor-not-allowed"
                >
                  ❌ Reject Loan
                </button>
                <button
                  onClick={() => handleReview('approve')}
                  disabled={loading}
                  className="px-8 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700 transition-all hover:shadow-lg disabled:bg-gray-400 disabled:cursor-not-allowed"
                >
                  ✅ Approve Loan
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
